import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ContextProvider } from "./context/userContext";
import NavBar from "./_component/NavBar";
import { ToastContainer } from "react-toastify";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Todo Web Application",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} max-w-[1120px] mx-auto`}>
        <ContextProvider>
        <ToastContainer />
        <NavBar/>
        {children}
        </ContextProvider>
      </body>
    </html>
  );
}
